pdfConfig: !pdfConfig
  compressed: false
  author: "ANT - Swisstierras Colombia"
  subject: "ANT - Swisstierras Colombia"
  creator: "ANT - Swisstierras Colombia"

throwErrorOnExtraParameters: true
transparentTileErrorColor: "rgba(78, 78, 255, 125)"
opaqueTileErrorColor: "rgba(255, 155, 155, 0)"
jdbcDrivers:
    - org.postgresql.Driver
templates:
  A4 portrait: !template
    pdfConfig: !pdfConfig
      title: "Plano predial ANT"
    reportTemplate: report.jrxml
    jdbcUser: "{DB_USER}"
    jdbcPassword: "{DB_PASSWORD}"
    jdbcUrl: "jdbc:postgresql://{DB_HOST}:{DB_PORT}/{DB_NAME}"
    attributes:
      id: !integer
        default: null
      criterio_punto_inicial: !integer
        default: 1
      zone: !string
        default: ''
      nameWhoElaborated: !string
        default: ''
      licenseWhoElaborated: !string
        default: ''
      nameWhoRevised: !string
        default: ''
      licenseWhoRevised: !string
        default: ''
      observationsReport: !string
        default: ''
      title: !string
        default: "CERTIFICADO PLANO PREDIAL CATASTRAL"
      datasetName: !string
        default: null
      map: !map
        maxDpi: 400
        width: 540
        height: 400
      scalebar: !scalebar
        width: 180
        height: 20
        default:
          align: "right"
          fontSize: 8
      northArrowDef: !northArrow
        size: 40
        default:
          graphic: "file://images/NorthArrow.png"
      overviewMap: !overviewMap
        width: 265
        height: 215
        maxDpi: 400
        style: "file:///styles/bbox.sld"
      overlayLayers: !staticLayers
        default:
          layers:
            - type: "grid"
              renderAsSvg: true
              rotateLabels: false
              numberOfLines: [4,4]
              labelColor: "#000000"
              haloColor: "#ffffff"
              haloRadius: 1
              horizontalYOffset: 7
              font:
                size: 5
                name: ["Arial", "Helvetica", "Nimbus Sans L", "Liberation Sans", "FreeSans", "Sans-serif"]
              style:
                version: 2
                "*":
                    symbolizers:
                    - type: line
                      strokeDashstyle: "solid"
                      strokeWidth: 0.3
                      strokeColor: "#3c3c3c"
                      strokeOpacity: 0.5
    processors:
    - !addBackgroundLayers
      inputMapper:
          overlayLayers: staticLayers
          map: map
    - !reportBuilder
      directory: '.'
    - !createMap
      inputMapper:
        map: map
      outputMapper:
        mapSubReport: mapSubReport1
        mapContext: mapContext1
    - !createOverviewMap {}
    - !createScalebar
      inputMapper:
        scalebar: scalebar
        mapContext1: mapContext
      outputMapper:
        scalebarSubReport: scalebarSubReport1
    - !createNorthArrow
      inputMapper:
        northArrowDef: northArrow
      outputMapper:
        northArrowSubReport: northArrowSubReport1